[project]
name = "shaf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "httpx>=0.28.1",
    "langchain-anthropic>=0.3.21",
    "mcp-use>=1.3.11",
    "mcp[cli]>=1.16.0",
]
